name: Terraform -  Azure Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  TF_VERSION: 1.9.6
  TF_VARS_FILE: ./enviorenment_tfvars/terraform.tfvars
  WORKING_DIR: ./

jobs:
  terraform-deploy:
    name: Terraform Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/terraform-hector:latest
          echo "Construyendo imagen Docker desde ./app..."
          docker build -t $IMAGE_NAME ./app

          echo "â¬†Subiendo imagen a Docker Hub hector..."
          docker push $IMAGE_NAME
          echo "Imagen subida: $IMAGE_NAME"
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
#      - name: Azure Login
#        uses: azure/login@v2
#        with:
#          client-id: ${{ secrets.AZURE_CLIENT_ID }}
#          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform plan -var-file=${{ env.TF_VARS_FILE }} -out=tfplan.out

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform apply -auto-approve tfplan.out
